config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController


  def index
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular coffee icon"></i>
  Say Something
</h4>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui feed">
         </div>
        </div>
        <div class="extra content">
          <form class="ui reply form">
            <div class="field">
              <div class="ui fluid icon input">
                <input type="text" placeholder="Enter a message...">
                <i class="bordered inverted yellow edit icon"></i>
              </div>
            </div>
           </form>
        </div>
      </div>
</div>
<div clas="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="active item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>

</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class: "item" %>
<a class="item">
  Messages
</a>
<div class = "right menu">
  <div class="ui dropdown item">
    Account <i class ="dropdown icon"></i>
    <div class="menu">
      <%= link_to "Log in", login_path, class: "item" %>
      <a class="item">Log out</a>
      <a class="item">Sign up</a>
    </div>
  </div>
  <div class="item">
    <div class="ui primary button">Sign Up</div>
  </div
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
      <%= render 'layouts/navigation' %>
      </div>
    </div>
    </div>


        <%= yield %>




  </body>
</html>